export * from './permission.enum';
export * from './permission.model';
export * from './create.input';
export * from './update.input';
export * from './permission-order';
export * from './permission-pagination.input';
export * from './permission-where';
export * from './permission.output';
export * from './permission-select.output';
