export const IconConfig: { [key: string]: string } = {
  folder: '/assets/file-icons/folder.svg',
  'folder-open': '/assets/file-icons/folder-open.svg',
  file: '/assets/file-icons/file.svg',
  css: '/assets/file-icons/css.svg',
  dockerfile: '/assets/file-icons/dockerfile.svg',
  git: '/assets/file-icons/git.svg',
  html: '/assets/file-icons/html.svg',
  ico: '/assets/file-icons/ico.svg',
  java: '/assets/file-icons/java.svg',
  png: '/assets/file-icons/png.svg',
  jpg: '/assets/file-icons/jpg.svg',
  'json-data': '/assets/file-icons/json-data.svg',
  json: '/assets/file-icons/json.svg',
  md: '/assets/file-icons/md.svg',
  svg: '/assets/file-icons/svg.svg',
  scss: '/assets/file-icons/scss.svg',
  less: '/assets/file-icons/less.svg',
  ts: '/assets/file-icons/ts.svg',
  prisma: '/assets/file-icons/prisma.svg'
};
